// Date: 07/08/2013 19:33:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modeldiamond anvil extends ModelBase
{
  //fields
    ModelRenderer BASE;
    ModelRenderer BASE;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
  
  public Modeldiamond anvil()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BASE = new ModelRenderer(this, 0, 53);
      BASE.addBox(0F, 0F, 0F, 3, 1, 10);
      BASE.setRotationPoint(-6F, 23F, -5F);
      BASE.setTextureSize(64, 64);
      BASE.mirror = true;
      setRotation(BASE, 0F, 0F, 0F);
      BASE = new ModelRenderer(this, 0, 53);
      BASE.addBox(0F, 0F, 0F, 3, 1, 10);
      BASE.setRotationPoint(3F, 23F, -5F);
      BASE.setTextureSize(64, 64);
      BASE.mirror = true;
      setRotation(BASE, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 42);
      Shape1.addBox(0F, 0F, 1F, 9, 2, 8);
      Shape1.setRotationPoint(-4.5F, 21F, -5F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 33);
      Shape2.addBox(0F, 0F, 0F, 8, 2, 6);
      Shape2.setRotationPoint(-4F, 19F, -3F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 24);
      Shape3.addBox(0F, 0F, 0F, 10, 1, 7);
      Shape3.setRotationPoint(-5F, 18F, -3.5F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 12);
      Shape4.addBox(0F, 0F, 0F, 12, 2, 9);
      Shape4.setRotationPoint(-6F, 16F, -4.5F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 14, 2, 9);
      Shape5.setRotationPoint(-7F, 14F, -4.5F);
      Shape5.setTextureSize(64, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BASE.render(f5);
    BASE.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
