// Date: 8/13/2013 3:13:37 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelWaterwheel extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
  
  public ModelWaterwheel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(-28F, -18.8F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, -0.7853982F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(-11F, -35.8F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(-25F, -18.8F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 1.570796F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(-10.6F, 19.2F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(-25.6F, 3.1F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0.7853982F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(30F, -18.8F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 1.570796F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(13F, -35.8F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0.7853982F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 3, 16);
      Shape1.setRotationPoint(11F, 20F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, -0.7853982F);
      Shape2 = new ModelRenderer(this, 0, 106);
      Shape2.addBox(0F, 0F, 0F, 6, 6, 16);
      Shape2.setRotationPoint(-3F, -9F, -8F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 24, 3, 3);
      Shape3.setRotationPoint(3F, -7.5F, 4F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 23, 3, 3);
      Shape3.setRotationPoint(-25F, -7.5F, 4F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 24, 3, 3);
      Shape3.setRotationPoint(3F, -7.5F, -7F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 23, 3, 3);
      Shape3.setRotationPoint(-25F, -7.5F, -7F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 24, 3, 3);
      Shape3.setRotationPoint(-1.5F, -9F, 3F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -1.570796F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 23, 3, 3);
      Shape3.setRotationPoint(-1.5F, 20F, 3F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -1.570796F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 24, 3, 3);
      Shape3.setRotationPoint(-1.5F, -9F, -7F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -1.570796F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 23, 3, 3);
      Shape3.setRotationPoint(-1.5F, 20F, -7F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -1.570796F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 52, 3, 3);
      Shape3.setRotationPoint(-18.8F, 10F, -2F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -0.7853982F);
      Shape3 = new ModelRenderer(this, 0, 37);
      Shape3.addBox(0F, 0F, 0F, 54, 3, 3);
      Shape3.setRotationPoint(-18F, -26F, -2F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.7853982F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 2, 26);
      Shape4.setRotationPoint(-1F, -7F, -12.6F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 70);
      Shape5.addBox(0F, 0F, 0F, 4, 4, 2);
      Shape5.setRotationPoint(-2F, -8F, -13F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 70);
      Shape5.addBox(0F, 0F, 0F, 4, 4, 2);
      Shape5.setRotationPoint(-2F, -8F, 13F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
