// Date: 8/8/2013 4:51:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelJug extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape1;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
  
  public ModelJug()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 74, 32);
      Shape1.addBox(0F, 0F, 0F, 10, 4, 10);
      Shape1.setRotationPoint(-4.533333F, 20F, -5F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 12, 8, 12);
      Shape2.setRotationPoint(-5.533333F, 13F, -6F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 88, 17);
      Shape1.addBox(0F, 0F, 0F, 10, 5, 10);
      Shape1.setRotationPoint(-4.533333F, 10F, -5F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 24, 22);
      Shape3.addBox(0F, 0F, 0F, 4, 6, 4);
      Shape3.setRotationPoint(-1.533333F, 6F, -2F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 24);
      Shape4.addBox(0F, 0F, 0F, 6, 2, 6);
      Shape4.setRotationPoint(-2.533333F, 5F, -3F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 87, 16);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 6);
      Shape5.setRotationPoint(0F, 11F, -6.94F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 88, 18);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 11);
      Shape5.setRotationPoint(0F, 22F, -8F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 1.570796F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 82, 17);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 6);
      Shape5.setRotationPoint(0F, 21F, -7F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape1.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
